# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - project is defined
    - zone is defined
    - custom_vars.reservation_name is defined
    - custom_vars.reservation_machine_type is defined
    - custom_vars.reservation_machine_count is defined

- name: Create Reservation
  register: create_reservation_result
  changed_when: create_reservation_result.rc == 0
  ansible.builtin.command: gcloud compute reservations create {{ custom_vars.reservation_name }} --vm-count={{ custom_vars.reservation_machine_count }} --machine-type={{ custom_vars.reservation_machine_type }} --require-specific-reservation --project={{ project }} --zone={{ zone }}
